import { Inter } from "next/font/google";
import "./globals.css";
import SideNavigation from "@/components/Navbar/SideNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative">
          <SideNavigation />
          <div className="lg:ml-[300px] md:ml-[270px] ml-[220px] p-4">
            <h3 className="text-2xl text-center my-4">Rick & Morty Characters</h3>
            {/* This margin-left value should match the width of SideNavigation */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
