import { Inter } from "next/font/google";
import "./globals.css";
import Hamburger from "../components/Navbar/Hamburger";
import SideNavigation from "../components/Navbar/SideNavigation";
import ContextProvider from "../constants/ContextApi";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Suspense>
          <div className="relative">
            <SideNavigation />
            <div className="lg:ml-[300px] md:ml-[270px] ml-0 sm:p-4 p-2">
              <Hamburger />
              <h3 className="text-2xl text-center my-4">
                Rick & Morty Characters
              </h3>
              {children}
            </div>
          </div>
          </Suspense>
        </ContextProvider>
      </body>
    </html>
  );
}
